language: php
php:
  - 7.1.9
 
before_script:
 - composer require --dev friendsofphp/php-cs-fixer
 - composer require --dev sensiolabs/security-checker
script:
    - web/app.php
notifications:
    slack: esgienv:P41xWxouoCKCqrJVOsVtfCNR
