<?php

namespace AppBundle\Repository;

/**
 * bon_mauvais_membreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bon_mauvais_membreRepository extends \Doctrine\ORM\EntityRepository
{
}
