<?php

namespace AppBundle\Repository;

/**
 * ChatsalonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatsalonRepository extends \Doctrine\ORM\EntityRepository
{
}
