<?php

namespace AppBundle\Repository;

/**
 * Inviter_au_salonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inviter_au_salonRepository extends \Doctrine\ORM\EntityRepository
{
}
