<?php

namespace AppBundle\Repository;

/**
 * ModerateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModerateurRepository extends \Doctrine\ORM\EntityRepository
{
}
