<?php

namespace AppBundle\Repository;

/**
 * Send_request_salonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Send_request_salonRepository extends \Doctrine\ORM\EntityRepository
{
}
